# -*- coding: utf-8 -*-
"""CorrelationCalculation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PcPRxNS4tjZx9Tlvu0RxfRzLFvXFw19H

Correlation Calculation File

Takes in the processed data and creates a file correlations between each KC.

Also calculates p-value for each correlation

EDM Project, Spring 2022

Imports
"""

!pip install pandas

import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import re

from pandas.api.types import is_string_dtype
from pandas.api.types import is_numeric_dtype

import scipy.stats

nltk.download('punkt')
nltk.download('stopwords')

"""Correlation and P-Value Calculation"""

#Data was encoded using a different script, it is used as input here
inputFile = 'dataHotEncoded.csv'
inputData = pd.read_csv(inputFile, sep=',', skiprows=(0), header=(0))

corrDict = {}

#For each variable, calculates the correlation and p-value between two distinct variables
#Saves results in dictionary
for column1 in inputData:
  for column2 in inputData:
    if is_numeric_dtype(inputData[column1]) and is_numeric_dtype(inputData[column2]):
      if column1 != column2:
        key = column1 + ',' + column2
        #c is correlation, p is p value
        c, p = scipy.stats.pearsonr(inputData[column1], inputData[column2])
        corrDict[key] = (c,p)

#Transfering results from dictionary into output file
with open('correlation.csv', 'w') as outfile:
  for key in corrDict:
    outfile.write(key + ',' + str(corrDict[key]) + '\n')