# -*- coding: utf-8 -*-
"""CorrelationCalculation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PcPRxNS4tjZx9Tlvu0RxfRzLFvXFw19H

Imports
"""

!pip install pandas

import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import re

from pandas.api.types import is_string_dtype
from pandas.api.types import is_numeric_dtype

import scipy.stats

nltk.download('punkt')
nltk.download('stopwords')

"""Correlation Calculation"""

inputFile = 'dataHotEncoded.csv'
inputData = pd.read_csv(inputFile, sep=',', skiprows=(0), header=(0))

#for column in inputData:
#  if column != 'Question' and 'KC' not in column:
#    inputData[column] = pd.to_numeric(inputData[column])

corrDict = {}

for column1 in inputData:
  for column2 in inputData:
    if is_numeric_dtype(inputData[column1]) and is_numeric_dtype(inputData[column2]):
      if column1 != column2:
        key = column1 + ',' + column2
        c, p = scipy.stats.pearsonr(inputData[column1], inputData[column2])
        corrDict[key] = (c,p) #np.corrcoef(inputData[column1], inputData[column2])[0,1]

with open('correlation.csv', 'w') as outfile:
  for key in corrDict:
    print((key + ': ' + str(corrDict[key])))
    outfile.write(key + ',' + str(corrDict[key]) + '\n')