# -*- coding: utf-8 -*-
"""HotEncoding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gRkmG63-qQO258UiSs6A8a47Clsan6Sp

Hot Encoding File

Takes in the processed data and creates a file with hot encoded KCs per question.

EDM Project, Spring 2022

Import statements
"""

!pip install pandas

import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import re

import scipy.stats

nltk.download('punkt')
nltk.download('stopwords')

"""Hot Encoding"""

#Input file is the cleaned data
inputFile = 'Language_Processed_Data.csv'
inputData = pd.read_csv(inputFile, sep=',', skiprows=(0), header=(0))

#Creating the hot encoding for each KC
hotEncodedData = pd.get_dummies(inputData, columns=['KC0','KC1','KC2','KC3'])
hotEncodedData.to_csv('hotEncodingMultipleKCs.csv', index=False)

#Since KCs appear multiple times, we combine the columns that refer to the same KC
#Each KC will now be its unique column with 1/0 values for each question, depending if that KC is present or not.
for column1 in hotEncodedData:
  for column2 in hotEncodedData:
    if column1[3:] == column2[3:]:
      for (index, value) in enumerate(hotEncodedData[column1]):
        if hotEncodedData[column1][index] == 1 or hotEncodedData[column2][index] == 1:
          hotEncodedData[column1][index] = 1
          hotEncodedData[column2][index] = 1

#Writing encoded data to file
hotEncodedData.to_csv('hotEncodingCombinedKCs.csv', index=False)