# -*- coding: utf-8 -*-
"""HotEncoding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gRkmG63-qQO258UiSs6A8a47Clsan6Sp

Import statements
"""

!pip install pandas

import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import re

nltk.download('punkt')
nltk.download('stopwords')

inputFile = 'Language_Processed_Data.csv'
inputData = pd.read_csv(inputFile, sep=',', skiprows=(0), header=(0))

hotEncodedData = pd.get_dummies(inputData, columns=['KC0','KC1','KC2','KC3'])
hotEncodedData.to_csv('hotEncodingMultipleKCs.csv', index=False)

for column1 in hotEncodedData:
  for column2 in hotEncodedData:
    if column1[3:] == column2[3:]:
      for (index, value) in enumerate(hotEncodedData[column1]):
        if hotEncodedData[column1][index] == 1 or hotEncodedData[column2][index] == 1:
          hotEncodedData[column1][index] = 1
          hotEncodedData[column2][index] = 1

hotEncodedData.to_csv('hotEncodingCombinedKCs.csv', index=False)

inputFile = 'dataHotEncoded.csv'
inputDataHotEncoded = pd.read_csv(inputFile, sep=',', skiprows=(0), header=(0))